spring:
  application:
    name: item-service
  cloud:
    config:
      override-none: true
      
  rabbitmq:
    host: 192.168.129.149
    port: 5672
    username: pdadmin
    password: pdadmin
      
server:
  port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka