spring:
  application:
    name: order-service
  cloud:
    config:
      override-none: true
    
  rabbitmq:
    host: 192.168.129.149
    port: 5672
    username: pdadmin
    password: pdadmin
    
server:
  port: 8201

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
      
feign:
  hystrix:
    enabled: true
    
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream